### PR TITLE
Adjust Yellow

### LINKED ISSUE #19: Make yellow more orange
By switching the hue start and end values, we can make Yellow a bit less brown.

```
hue_start: 50,
hue_end: 40,
```
## Before

Screen Shot 2019-11-27 at 10 48 43 AM

## After

Screen Shot 2019-11-27 at 10 48 18 AM

### PR DESCRIPTION
**Pull request by porada**
Inspired by #19, this PR attempts to make the most our of Yellow by making the brighter end a little more saturated and turning some of the brown-ness of the darker end into orange.

#### Before

Screenshot

#### After

Screenshot

The examples can be currently previewed using Now (see below).

Fixes #19.

### CODE REVIEW

**Comment by davewhitley** [comment]
Did a quick comparison of all 3

image



- I love how golden the lighter shades are on this PR (0–30). It's less orangey than my attempt in #19. Those shades look "yellow" to me.
- The darker shades (60-100) do look a bit less brown to me like you said. I think I could go either way — the brownness of #19 seems more "neutral yellow" to me (neither too orange or too green). I don't have a strong opinion on that though.
- The main feedback I have is the transition between 40 and 50. In this PR, I perceive a hard jump in hue. 40 looks much more green and is almost the same as the 40 shade of the current yellow. The effect is heightened when placed next to the 50 shade, which is quite orangey.

**Comment by porada** [comment]
Thanks for the review, @davewhitley!

You’re right, Yellow 40 is exactly the same as the one from the current version. To be honest, I was curious if I’m going to get called out on it. 🙂

I’ll take a look at it tomorrow with fresh eyes and orange it up for a smoother transition.

**Comment by porada** [comment]
@davewhitley, let me know what you think now. I adjusted the shades 40–80 to land somewhere closer to #19.

**Comment by davewhitley** [comment]
looks good!

**Comment by porada** [comment]
Thanks! Merging soon.

**Pull request merged**
