### PR TITLE
Jetpack: make Green 40 the default color

### PR DESCRIPTION
**Pull request by keoshi**
#### Changes

* Make Jetpack Green 40 the default Jetpack color.

More context on this decision here: p6TEKc-3tD#comment-7312

#### Screenshots

Before | After
--|--
image | image
image | image
image | image
image | image

### CODE REVIEW

**Comment by porada** [comment]
Thanks for the submission! Rebased and merged. Releasing shortly…

**Comment by keoshi** [comment]
Thank you, @porada !

**Comment by porada** [comment]
Released as `2.5.0`.

@keoshi — Any chance you could also bump the version number in Calypso?

**Comment by keoshi** [comment]
Haven't done it before but happy to do that, yeah! Am I looking in the right place here?

- https://github.com/Automattic/wp-calypso/blob/eb9dd7c84bde69b517547ab8143e07e40c26023d/package.json
- https://github.com/Automattic/wp-calypso/blob/c41f5a70c3a3cdfa23f3da6004261007f5f978d3/client/package.json#L23

If so, it looks like it never got updated to 2.4.0? I just want to be sure that's where you update it.

**Comment by porada** [comment]
OK, looks like I skipped the client package the last time.

I usually update all the references I can find in the repo to the most recent version number without any range modifiers (like `^`), because we manage these updates manually anyway (so the plain `"2.5.0"` will do in this case). Once the PR has merged, I also publish a new version of `@automattic/calypso-color-schemes`.

Feel free to assign me as a reviewer, but let me know in case you’d rather I handled the PR. 🙂

**Pull request merged**
