### PR TITLE
Add Swift file distribution

### PR DESCRIPTION
**Pull request by jkmassel**
This PR:

1. Adds a Swift distribution that's lighter than the `xcassets` catalogue.
2. Adds a build script for it.
3. Makes this repo into a Swift package that can be referenced directly by any Swift project.

### CODE REVIEW

**Comment by porada** [comment]
@jkmassel — Thanks for the addition! Could you please move the code to a separate file to keep the builders focused? `builders/ios-swift-raw-data-from-json.js` or similar.

**Comment by porada** [comment]
Let me know when you’re ready with the PR. I can then handle the merge plus the new release.

**Comment by jkmassel** [comment]
Hi @porada – should be good to go, thank you!!

**Comment by porada** [comment]
I just published `@automattic/color-studio@3.0.2` to `npm`, but I’m not sure if we should publish this to a Swift-oriented directory as well. Let me know.

Before publishing, I also moved `ColorStudioPalette.swift` under `dist/ios-swift` for consistency (30e14311771b3d69fbd7412bb6cac85b391a2b87). I hope that doesn’t break anything.

**Pull request merged**
