### PR TITLE
Updates deprecated WordPress Blue

### PR DESCRIPTION
**Pull request by javierarce**
Updates the deprecated WordPress Blue based on the [new blueberry shades](https://www.figma.com/design/eqlepL7MHifK8Bgr1OWqLr/Dotcom-Design-Library?node-id=15746-759&t=YkA2ShvlSnLzEose-4)

image

### CODE REVIEW

**Comment by niranjan-uma-shankar** [comment]
Thanks for getting this shipped. Can we mark [this issue](https://github.com/Automattic/martech/issues/3197) completed?

**Comment by javierarce** [comment]
I think we still need to [update the npm package](https://www.npmjs.com/package/@automattic/color-studio) with the new version (2.6.1). I'm not sure how that's done (maybe directly through Vercel?)

**Comment by porada** [comment]
I’ll take care of this. Stay tuned 🙂

**Comment by javierarce** [comment]
Thanks, @porada!

**Comment by porada** [comment]
`@automattic/color-studio@3.0.1` is up. Figma updates and P2 update to follow shortly.

**Pull request merged**
