### PR TITLE
Add Vibrant Blue

### PR DESCRIPTION
**Pull request by porada**
This pull request aims to align our unified color palette with the draft of the visual playbook that was recently published internally. That will allow us to relay the updates to Calypso and our other apps.

Luckily, most of the secondary brand colors are already aligned with Color Studio. We only need to make room for the Blue and Light Blue defined in the playbook (I’ll prefix their names with `Playbook` from now on).

Here’s my suggestion: 

### Let’s make the current Blue strip more vibrant to match Playbook Blue.

That’s without touching WordPress Blue at all and without changing the Blue 80+ shades (Playbook Dark Blue and darker blues). WordPress Blue will stay as-is for now, but it should be considered deprecated.

Making Blue more vibrant feels like an iterative improvement. Another blue in the palette would only make things more confusing.

#### Previews

You can see how that will affect our apps using the previews below (please ignore the fact the UIs are a bit outdated):

* Calypso: [dashboard](https://color-studio-git-blue.a8c.vercel.app/examples/calypso-dashboard.html), [login screen 1](https://color-studio-git-blue.a8c.vercel.app/examples/calypso-login-start.html), [login screen 2](https://color-studio-git-blue.a8c.vercel.app/examples/calypso-login-2fa.html), and [components](https://color-studio-git-blue.a8c.vercel.app/examples/calypso-components.html).
* Mobile app: [light mode](https://color-studio-git-blue.a8c.vercel.app/examples/android-bright-theme.html) and [dark mode](https://color-studio-git-blue.a8c.vercel.app/examples/android-dark-theme.html).

If I hadn’t told you these used a different blue, there’s a slight chance you might not even notice. That’s probably the best argument for replacing the old Blue with the new vibrant version.

#### Changes

I made sure that Playbook Blue and Playbook Dark Blue maintained their values defined in the playbook. Unfortunately, Playbook Light Blue was so divergent from our palette that I couldn’t obtain the exact same value.

While the above was easy with Playbook Dark Blue (which was the same as Blue 80), obtaining Playbook Blue came at a slight expense of the overall shade consistency:

ezgif-2-72d98e8eb0b1

In an ideal case scenario, there should be no visible differences in the grayscale tiles (tip: you can toggle the grayscale mode in [Color Studio](https://color-studio.blog) with `control`+`G`). While this isn’t a big deal, this _could_ potentially result in uneven contrasts between some blue-on-blue color treatments.

The visual playbook is still fresh, so if we’re okay with iterating on the very color values defined in it, I can design a more consistent blue strip that will maintain all Playbook Blue’s features and will work better with the rest of our palette (becoming an even better drop-in replacement for the old blue). @ballio2000 @pablohoneyhoney, please let me know if I have your green light on this part.

### Next Steps

* Please note that this pull request is strictly about standardizing the new colors. We can discuss the strategy of phasing out the old WordPress Blue here, too, but that part will ultimately have to be carried out outside of this PR. 
* If we have a consensus here, I’ll release these changes in a new version of Color Studio and submit it to Calypso in a separate PR.

---

Please let me know if there are any questions. ✌️

### CODE REVIEW

**Comment by pablohoneyhoney** [comment]
Worth getting eyes and agreement across teams @mattmiklic @olaolusoga @ballio2000 
And test it in a few more scenarios. 

cc @davemart-in

**Comment by ballio2000** [comment]
This is feeling good to me, thanks for getting this started, Dom. We're already using this newer palette in marketing work, so it'd be good to incorporate it into Color Studio. 

One idea to avoid adding another new color is to tweak the Light Blue. Perhaps we can grab a lighter complementary value (something like #90C7F0) as Light Blue based on the new shades from #117AC9 to avoid adding a new color there. What do you think, @porada.

**Comment by davemart-in** [comment]
This is exciting! 

cc @lcollette and @sixhours

**Comment by porada** [comment]
> And test it in a few more scenarios.

@pablohoneyhoney, are there any specific scenarios you had in mind? I could add them to our existing [tests cases](https://color-studio-git-blue.a8c.vercel.app/examples). Anything we add today will also be helpful any time we start making major palette color changes, so I’m always for adding more specific scenarios.

> One idea to avoid adding another new color is to tweak the Light Blue. Perhaps we can grab a lighter complementary value (something like #90C7F0) as Light Blue based on the new shades from #117AC9 to avoid adding a new color there.

@ballio2000, apart from our slide templates, do we have any specific context where we’d use Light Blue for? I’m all for assigning one of the existing blue shades (after possible tweaks for better compliance), and being able to test it against specific examples would be useful. Another question: if we’re tweaking the value of Playbook Light Blue, is it okay if I also tweak Playbook WordPress Blue for better consistency with the rest of the colors and easier transition in the product UI?

**Comment by mattmiklic** [comment]
This looks good to me, but I'll share this with the other designers on WP mobile to give them a chance to weigh in (standard disclaimer about my colorblind eyes here).

**Comment by iamthomasbishop** [comment]
I gave these new blues a spin in various areas that we’re using inside the mobile editor (mostly blues 30, 40, and 50) to see how they play, and they seems to work very nicely, especially on iOS which has a more vibrant [system color palette](https://developer.apple.com/design/human-interface-guidelines/ios/visual-design/color/). As long as it passes the usual a11y tests, it gets the 👍/ :shipit:  from my side! // cc @kyleaparker

**Comment by ballio2000** [comment]
> @ballio2000, apart from our slide templates, do we have any specific context where we’d use Light Blue for? I’m all for assigning one of the existing blue shades (after possible tweaks for better compliance), and being able to test it against specific examples would be useful. Another question: if we’re tweaking the value of Playbook Light Blue, is it okay if I also tweak Playbook WordPress Blue for better consistency with the rest of the colors and easier transition in the product UI?

I believe we've used the light blue in the logged-out homepage. Usually it's used to complement one of the blues, dark + vibrant. Happy to use one of the lighter shades derived from the vibrant blue.

Tweaking playbook blue is OK. As long as it stays close to it -- as I think the current iteration is getting that nice, fresh vibrancy we're going for.

**Comment by porada** [comment]
@ballio2000 @pablohoneyhoney, I went ahead and made some consistency tweaks to the entire blue strip. And since we only use Celadon for marketing, I also optimized it a bit. How do [these colors](https://color-studio-git-blue.a8c.vercel.app/examples/marketing-playbook.html) feel to you now?

The examples I shared above still work, too:

> * Calypso: [dashboard](https://color-studio-git-blue.a8c.vercel.app/examples/calypso-dashboard.html), [login screen 1](https://color-studio-git-blue.a8c.vercel.app/examples/calypso-login-start.html), [login screen 2](https://color-studio-git-blue.a8c.vercel.app/examples/calypso-login-2fa.html), and [components](https://color-studio-git-blue.a8c.vercel.app/examples/calypso-components.html).
> * Mobile app: [light mode](https://color-studio-git-blue.a8c.vercel.app/examples/android-bright-theme.html) and [dark mode](https://color-studio-git-blue.a8c.vercel.app/examples/android-dark-theme.html).

In you want to compare any of the examples directly with the previous iteration of the vibrant blue, you can replace `blue` with `blue-backup` in the URL.

**Pull request merged**
