### PR TITLE
Add new Automattic color palette

### PR DESCRIPTION
**Pull request by keoshi**
This is a first iteration to be used primarily in Automattic for Agencies (A4A).

While it's a decent starting point, we'd like to keep improving it as we apply more of it to real interfaces, and uncover its limitations and quirks.

The primary brand color differs from what's been used in other materials a bit, but the new #24A3E0 color is very close anyhow that it could be implemented with no discernible difference.

image

Thanks @porada for clarifying some things this morning!

### CODE REVIEW

**Comment by cleacos** [comment]
Should we remove/overwrite the `dist/preview.png` file? It seems we are overwriting that file with a sample of 2 colors.

**Comment by keoshi** [comment]
@porada Did I do something wrong here with the image? Seems to be heavily cropping it. Would appreciate if you can take a look and review the PR too. Thank you!

**Comment by porada** [comment]
@keoshi — Thanks for the submission!

Would you be open to renaming the new color to `Automattic Blue` or `A8C Blue` for consistency with other brand colors?

I’ll take a look at the screenshot issue. Feel free to revert the file for now.

**Comment by keoshi** [comment]
@porada Updated the color scheme name to `Automattic Blue`. Tried with `A8C Blue` but Lodash's [`kebabCase()`](https://lodash.com/docs/4.17.15#kebabCase) apparently splits up letters and numbers and was generating `--studio-a-8-c-*` variable names, which seemed very error prone.

Apart from that, I've also tweaked the `builders/preview-from-docs.js` to correctly generate the image. Related code is here, but might need more tweaking to make it future-proof: https://github.com/Automattic/color-studio/pull/633/files#diff-4e87c8ce9c3adb9d19a2345c4878f849287ba0cd1fac6a4bb4c9a09a6db526e3R15

This is now ready for another review @cleacos & @porada. Thank you both!

**Comment by cleacos** [comment]
It looks good to me.

It seems we have to regenerate/overwrite the `preview.png` file:

https://github.com/Automattic/color-studio/pull/633/files

**Comment by keoshi** [comment]
> It seems we have to regenerate/overwrite the `preview.png` file:

Solved the conflict there. This is ready for another review and final merge if everything looks good. cc @porada

**Comment by cleacos** [comment]
@keoshi you have my virtual 👍 I'm not familiar with this package. Good job adding the A4A colors!

**Comment by porada** [comment]
The new color is now available in `@automattic/color-studio@2.6.0`. Thanks again for the submission 🙂

**Pull request merged**
