### PR TITLE
Final Color Tweaks

### PR DESCRIPTION
**Pull request by drw158**
More saturation on most colors and hue tweaks for Blue and Green.

I increased **saturation** on most colors so that the colors were more consistent with each other (trying to bring them all to the same level of saturation, optically). I think increasing saturation will also help with the usability of the status colors (green, red). I noticed that now some of the colors are accessible on white for the 40 shade. Not sure if this will be an issue.

For **hue**, I adjusted Green and Blue.

Blue: I ran with your idea of having 2 different blues, and I tried to move Blue more towards violet to distinguish it more from Airo. Hopefully the saturation and hue changes will also make link colors more accessible. I liked how this design system had a "sky" (Airo in our case) and regular "blue":

Screen Shot 2019-07-02 at 4 06 45 PM

Green: I moved Green more towards blue just a tad. This makes it a little bit less yellow. It might not make a huge difference, but apparently using more cool toned greens is better for red-green color blind folks. Subjectively, I also think Green is more in line with the other colors now.

Note that I had to adjust the lum_start on Blue by one so that the dark mode a11y tests would pass.

Easiest to see changes by opening master in another tab and switching. Or, use these 2 screenshots for reference.

Before
master

After
new

### CODE REVIEW

**Comment by drw158** [comment]
Example of how the new Blue changes the marketing example:

Screen Shot 2019-07-02 at 4 46 14 PM
Screen Shot 2019-07-02 at 4 46 27 PM

**Comment by porada** [comment]
Thanks for the pull request. I’ll take a look at it with fresh eyes tomorrow.

Permission to commit to this branch? We could do a little back and forth.

**Comment by drw158** [comment]
Sure!

**Comment by mattmiklic** [comment]
> more cool toned greens is better for red-green color blind folks

💯 This is very true in my experience.

**Comment by porada** [comment]
Hey @drw158, as you probably noticed, there have been some bigger changes in the master, so I reapplied your tweaks on top of it. I split your changes into separate color-specific commits, so that they’re a little easier to see and discuss.

I skipped the following adjustments:

* Red, Orange, and Yellow tweaks. They all received a facelift in the master.
* Blue → Indigo. When Blue turns Indigo, it loses its sentiment on the brand and marketing front. The idea of a separate product and brand blues in the first place wasn’t to have a more distinctive difference between them, but to make them complementary. With the renamed _WordPress Blue,_ the matter of when we use each has become clearer, so I’m pushing back. 🙂 If anything, I’ll want to make WordBlue Blue 10–40 a little more desaturated.

Also:

* The old Green has become Jetpack Green, which opened up a window for better improvements to the new Green (if need be). 🌱

The current state can be browsed [with this link](https://color-studio-a9wl5oz0u.now.sh).

As a next step, I’ll take a stab making the palette a little more consistent after all of those changes (going on through separate tracks). I think we’re very close, though. I’ll ping you when I’m done.

**Comment by drw158** [comment]
Thank you!

> Blue → Indigo. When Blue turns Indigo, it loses its sentiment on the brand and marketing front. The idea of a separate product and brand blues in the first place wasn’t to have a more distinctive difference between them, but to make them complementary. With the renamed WordPress Blue, the matter of when we use each has become clearer, so I’m pushing back. 🙂 If anything, I’ll want to make WordBlue Blue 10–40 a little more desaturated.

I'm not sure how marketing will use Blue and WP Blue, but it seems like having 2 different blues would be more valuable, just like having 2 different hues of green (Green and Celadon). 

On the product side, I don't think we'd use both WP Blue and Blue together, unless there was a brand purpose, like displaying the logo. For everything else though, we'd use Blue for UI. After sitting with the idea of 2 blues in the UI for awhile (and looking at the Calypso example), I don't think it's a good idea.

- The 2 blues doesn't fit our color system of having 1 primary and 1 secondary color.
- It's been much simpler and nicer to use 1 blue for everything (brand and product), even though the brand blue has proven to be not quite bright enough for links and such.
- Not so long ago we had 2 blues in Calypso (WordPress Blue and Medium Blue). It turned out to be very confusing and it was unclear when to use which one, and they were used interchangeably. I always hated that system, and I think consolidating to 1 blue has been great.

That being said, I'm still open to having 2 blues overall, just not in the product, aside from a few exceptions like a plan color or the logo or something. I think I'd want illustrations to use Blue.

Here's a quick alternative that isn't quite as Indigo:

Not as Indigo
Screen Shot 2019-07-08 at 11 06 27 AM

More Indigo
Screen Shot 2019-07-08 at 11 07 01 AM

That turned out way more subtle than I thought 😅 . Even less indigo:

Screen Shot 2019-07-08 at 11 22 40 AM

**Comment by drw158** [comment]
> Red, Orange, and Yellow tweaks. They all received a facelift in the master.

> The old Green has become Jetpack Green, which opened up a window for more Calypso-specific improvements to the new Green (if need be). 🌱

> As a next step, I’ll take a stab making the palette a little more consistent after all of those changes (going on through separate tracks). I think we’re very close, though. I’ll ping you when I’m done.

Sounds good!

**Comment by porada** [comment]
> On the product side, I don't think we'd use both WP Blue and Blue together, unless there was a brand purpose, like displaying the logo. For everything else though, we'd use Blue for UI. After sitting with the idea of 2 blues in the UI for awhile (and looking at the Calypso example), I don't think it's a good idea.

Which color would you like to use for the top bar in Calypso? Blue or Indigo?

Calypso login screen

This screenshot uses the old Blue.

**Comment by porada** [comment]
I really don’t want us to ship a redesign. It’s was all about refinement from the very start.

> * The 2 blues doesn't fit our color system of having 1 primary and 1 secondary color.
> * It's been much simpler and nicer to use 1 blue for everything (brand and product), even though the brand blue has proven to be not quite bright enough for links and such.

While I agree, it’s all about making the right compromises.

* We can’t use the brand blue in UI for accessibility reasons.
* We can’t use product blue for brand and marketing purposes, because it’s a significant departure from all the materials we’ve launched and it undermines the efforts multiple teams put into building out the brand we have today. If our brand could rely on saturated colors from the very start, the palette would have been completely different as that would’ve opened up more possibilities.
* We can’t fit two blue colors into the system.

Which of those can we overcome the most easily?

My suggestion was to reconcile the first two points by splitting the single inaccessible blue into two compatible colors, which I suggested in the early phase of the project. Right now, I’m very worried by the fact **this undermines days of work I’ve put into the new palette.**

If we agree on going with the two blues, we can still work out the way they’ll look finally. But I need a clear decision how to continue working on this.

> Not so long ago we had 2 blues in Calypso (WordPress Blue and Medium Blue). It turned out to be very confusing and it was unclear when to use which one, and they were used interchangeably. I always hated that system, and I think consolidating to 1 blue has been great.

I was going to write proper guidelines which we didn’t have back then.

**Comment by mattmiklic** [comment]
FWIW I think the two shades of blue are helpful. It lets us use a blue that's brighter and easier to see for colorblind folks in the UI, without dramatically changing our brand color. I'm finding that they work well together when used in this way. The Stats screen in the app is a good example; we use the brand blue for the toolbar and app icon but product blues everywhere else.

Screen Shot 2019-07-08 at 1 58 28 PM
Simulator Screen Shot - iPhone Xs - 2019-07-08 at 13 59 14

**Comment by drw158** [comment]
> Which color would you like to use for the top bar in Calypso? Blue or Indigo?

Between **Blue** and **WordPress Blue**, I'd use Blue for the top bar in Calypso as well as the same bars in the WP mobile apps.

> We can’t use the brand blue in UI for accessibility reasons.

I don't think this is true. Afaik, we can use the current brand blue, it's just not ideal. Things would largely stay the same in the product, and we'll have to rely on other visual indicators like underlines, which we should be doing anyway.

> We can’t use product blue for brand and marketing purposes, because it’s a significant departure from all the materials we’ve launched and it undermines the efforts multiple teams put into building out the brand we have today. If our brand could rely on saturated colors from the very start, the palette would have been completely different as that would’ve opened up more possibilities.

Although I think having one saturated blue that could work for both marketing and product would be great, I realize that's "undoing" a lot of work that has been done the past year or so. Because of that, I don't suggest consolidating to 1 blue, in the foreseeable future at least.

> We can’t fit two blue colors into the system.

I think we can, in the overall system. In product, the 2 blues look too similar or not different enough — similar to our old system of using WordPress Blue and Medium Blue. Using the 2 blues (e.g. one blue for the top bar and one blue for buttons) looks like a visual mistake in some places, or least makes me question, "Why are those 2 blues different?")

Screen Shot 2019-07-08 at 1 02 49 PM

**Comment by porada** [comment]
> 2 blues look too similar or not different enough

That’s by design. 🙂

**Comment by porada** [comment]
This branch ended up being mostly about leveling the colors out for better step consistency. Some notes:

* My biggest takeaway from this branch is that each color reacts to luminosity levels in its own way. Inspired by [Mineral UI](https://uxplanet.org/designing-systematic-colors-b5d2605b15c), I ended up tweaking the values manually.
* Red, orange, yellow, and green have been optimized for how we actually use them in our apps (notice bars and status icons).
* With some deliberate sacrifices, I managed to bring back the guaranteed accessibility from shade 50 (#14).

The current state of this branch can be [browsed here](https://color-studio-b02cai15p.now.sh). A P2 update will follow. Hit `control-G` for grayscale preview.

I’m running out of time, so I’ll be merging this to master soon. If you spot any major issues, please report them in separate issues. 🙏

**Pull request merged**
